name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  java-test:
    uses: ./.github/workflows/java-test-reusable.yml

  docker-ci:
    needs: java-test
    uses: ./.github/workflows/docker-ci-reusable.yml





